parameters:
    nedwave_user.user_manager.class: Nedwave\UserBundle\Doctrine\UserManager
    nedwave_user.user_provider.class: Nedwave\UserBundle\Security\UserProvider

services:
    nedwave_user.user_manager:
        class: %nedwave_user.user_manager.class%
        arguments: [%nedwave_user.user_class%, @doctrine.orm.entity_manager, @security.encoder_factory]
    
    nedwave_user.user_provider:
        class: %nedwave_user.user_provider.class%
        arguments: [@nedwave_user.user_manager]
    
    nedwave_user.form.change_password:
        class: Nedwave\UserBundle\Form\ChangePasswordType
        arguments: [%nedwave_user.user_class%]
        tags:
            - { name: form.type, alias: nedwave_user_change_password }
    
    nedwave_user.form.registration:
        class: Nedwave\UserBundle\Form\RegistrationType
        arguments: [%nedwave_user.user_class%]
        tags:
            - { name: form.type, alias: nedwave_user_registration }